AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Jenkins Role"
Parameters:
  AttachJenkinsRoleARNs:
    Description: Required - Comma separated list of Jenkins Instance IAM Role.
    Type: CommaDelimitedList
  RoleName:
    Description: Required - Comma separated list of Jenkins Instance IAM Role.
    Type: String
Resources:
  JenkinsRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        Ref: AttachJenkinsRoleARNs
      RoleName:
        Ref: RoleName
  JenkinsInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: JenkinsRole
